services:
  builder:
    container_name: ${BUILD_CONT_NAME}
    build: ./builder
    user: ${USER_ID}:${GROUP_ID}
    environment:
      HOME: ${SRCROOT}/poky
    working_dir: ${SRCROOT}/poky
    volumes:
      - ${SRCROOT}:${SRCROOT}
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    stdin_open: true
    tty: true
    command: bash
